In [2]:
# module 6

import numpy as np
# all zeros matrics.
# how can we make an array which every value will be 0?
# we can do that with np.zero() method.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [2]:
# we can make 2d or 3d or any d zeros matrics also.
# all we have to do is to pass a list of values which will represent the shape of our array instead a value.
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# we can also use the zeros_like() method
# basically, this method allows us to copy any other matrix shape and change all the values as instructed.
b=np.array([[1,3,4,2,5,6,7],[4,8,3,5,2,3,7]])
print(b)
np.zeros_like(b)

[[1 3 4 2 5 6 7]
 [4 8 3 5 2 3 7]]


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [3]:
# all ones matrics.
# we can do that with np.ones() method.
np.ones([2,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
# we can also specify the datatype here.
np.ones([4,2,3], dtype="int32")

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [12]:
# we can also use ones_like() method.
np.ones_like(b)

[[1 3 4 2 5 6 7]
 [4 8 3 5 2 3 7]]


array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [2]:
# the function empty creates an array whose initial content is random and depends on the state of the memory
np.empty([2,5])

array([[1.96086573e+243, 6.01346953e-154, 2.03721912e+174,
        1.06112722e-153, 2.35566768e+251],
       [5.22373805e+257, 3.47819991e+069, 1.03542810e+208,
        1.06112833e-153, 1.17365078e+214]])

In [13]:
# we can also use empty_like() method.
np.empty_like(b)

array([[        0,         0,         0,         0,         0,         0,
                0],
       [        0,         0,         0,         0,         0, 993090402,
        879572531]])

In [10]:
# any other number matrix.
# we can do that with np.full() mathod.
# it takes 2 parameter.
# first arguement is the array shape and the second arguement is the other value.
np.full([4,2,3],8,dtype="int32")

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [11]:
# any other number
# we can also use the np.full_like method()
np.full_like(b,88)
# it will take two arguement.
# the first one is that array that we want to copy.
# the second one it the value

array([[88, 88, 88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88, 88, 88]])

In [7]:
# random decimal numbers
# we can do that by using the rand method from the random class of numpy.
# this is a little different than what we have done before.
# if we want to initialize multidimentional array, then we dont have to pass the list,
# instead of that we need to pass the shape without the list.
np.random.rand(2,3,2)
# it gives us random values from 0 to 1. here 1 is exclusive. 

array([[[0.67620657, 0.30938891],
        [0.80298031, 0.14683076],
        [0.16876821, 0.34455424]],

       [[0.31234492, 0.31441356],
        [0.18751879, 0.95904596],
        [0.91687852, 0.79420473]]])

In [9]:
# if we want to pass in the shape or the list which represents the shape,
# then we can do that by random.random_sample() method.
print(b.shape)
print(np.random.random_sample(b.shape))
print()
print(np.random.random_sample((2, 7)))

(2, 7)
[[0.62469119 0.4326429  0.73180927 0.69677058 0.56315679 0.60447296
  0.87592997]
 [0.55743121 0.81020532 0.96339933 0.02932299 0.68948531 0.9414909
  0.39876376]]

[[0.37472636 0.81017813 0.3132756  0.81935684 0.55361182 0.45772341
  0.30248903]
 [0.77382877 0.93499975 0.2030079  0.84975799 0.01142703 0.03797685
  0.43357397]]


In [10]:
# random integer numbers 
# we can use the randint() method from random library.
np.random.randint(100,size=(2,3,5))
# this method take two arguemnt, the first one is end value which would be exclusive.
# the second one is the size arguement which will be equal to our shape of the array.

array([[[34, 46, 37, 29, 14],
        [17,  4,  8, 62, 27],
        [16, 39, 25, 64, 56]],

       [[49, 94, 15, 68, 13],
        [99, 72, 80, 67, 56],
        [81, 11, 14, 66,  3]]])

In [4]:
# we can also add another arguement as the first guement of the randint() method.
# that arguement would be the start value.
np.random.randint(50,100,size=(2,3,5))
# we can also use negative values for our start and end arguements.

array([[[95, 86, 71, 73, 76],
        [54, 68, 73, 61, 93],
        [64, 79, 96, 79, 65]],

       [[51, 59, 93, 89, 67],
        [92, 69, 87, 50, 97],
        [64, 77, 99, 76, 62]]])

In [64]:
# if we want to create random decimal values array which doesn't in range of 0 to 1,
# then we caan use raandom.randn() function.
g=np.random.randn(3,4)
print(g)
# The main reason in this is an activation function,
# especially in our case where we use the sigmoid function.

[[-1.68062489 -1.16121878  2.15931303  1.55358664]
 [ 0.06684849  0.05104871  2.30490394  0.05323694]
 [ 0.09782335  2.29233956  0.0969062   0.78266329]]


In [3]:
# we can create an array of random "normal" values by random.normal() function.
print(np.random.normal(2,1,4))

[1.1874957  3.50975925 3.50207169 1.05464673]


In [25]:
# initializing identity matrix
# we can print the iudentity matrix by identity() function.
# this will take 1 arguemnt which indicates the shape of our identity matrix as it is a square matrix by nature.
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# repeat the arrays 
# we can do that with repeat() method.
arr=np.array([[3,2,4],[2,3,5]])
rep=np.repeat(arr,3, axis=0)
# repeat() takes two arguement.
# first one is the array.
# second one is the how many times we want to repeat the array.
# in numpy, it repeats the value by rows automatically.
# but we can change it to columns instead by adding an another arguement axis and setting that equal to 0.

# remember that,
# in numpy-
# column axis 0
# rows   axis 1
# and so on

rep

array([[3, 2, 4],
       [3, 2, 4],
       [3, 2, 4],
       [2, 3, 5],
       [2, 3, 5],
       [2, 3, 5]])

In [14]:
# we can print out equally spaced values between two certain values with numpy array.
# we can do that by linspace() method.
d=np.linspace(1,3,5)
# it takes 3 arguemnts first one is the start value, secong one is the end value which will be inclusive.
# and the last one is how many linspaced values that we want in that array.
# this is pretty much the like bins in the histograms which we have seen while working with matplotlib library. 
print(d)

[1.  1.5 2.  2.5 3. ]


In [15]:
# we have another method in numpy that is logspace()
# in linspace() the gap between two elements were same.
# but in logspace() the spacing between two values depends on the log of those.
e=np.logspace(1,40,5)
# it takes 3 arguemnts first one is the start value, second one is the end value which will be inclusive.
# and the last one is how many logspaced values that we want in that array.
print(e)
# so it will start from log10(1) and ends to log10(40) and all other numbers are in between of them.
# and in this case we will get 5 value in the array.

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [12]:
# indices()
# indices() will create a set of arrays (stacked as a one-higher dimensioned array),
# one per dimension with each representing variation in that dimension.

i=np.indices([3,3])
print(i)
# absically it gives us a three dimentional array.
# here the first value of the list is the number of row and the second value indicates the column in each 2d arrays,
# so it will give us the variation of 2d array in this case which is two types stacked in a 3 dimentional array.

# This is particularly useful for evaluating functions of multiple dimensions on a regular grid.

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [1]:
# we can also create arrays with comments.
# but for that we have to know working with regex in python.
# that i will learn a much moment later.

In [16]:
# challange
output=np.ones([5,5])
output[1:4,1:4]=np.zeros([3,3])
output[2,2]=9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])