In [10]:
# module 10

import numpy as np
c=np.array([[6, 4, 5, 6],[7, 6, 7, 7],[6, 6, 6, 6],[4, 4, 6, 5]])
print(c)

[[6 4 5 6]
 [7 6 7 7]
 [6 6 6 6]
 [4 4 6 5]]


In [11]:
# we can use statistics function in our numpy array.
print(np.min(c))
print(np.max(c))
print(np.mean(c))
print(np.sum(c))

4
7
5.6875
91


In [12]:
# we can use the axis arguement and set that equals to 1 for doing statistics function for every column
print(np.min(c,axis=1))
print(np.max(c,axis=1))
print(np.mean(c,axis=1))
print(np.sum(c,axis=1))

[4 6 6 4]
[6 7 6 6]
[5.25 6.75 6.   4.75]
[21 27 24 19]


In [13]:
# we can use the axis arguement and set that equals to 0 for doing statistics function for every row
print(np.min(c,axis=0))
print(np.max(c,axis=0))
print(np.mean(c,axis=0))
print(np.sum(c,axis=0))

[4 4 5 5]
[7 6 7 7]
[5.75 5.   6.   6.  ]
[23 20 24 24]
