In [63]:
# module 10

import numpy as np
c=np.array([[6, 4, 5, 6],[7, 6, 7, 7],[6, 6, 6, 6],[4, 4, 6, 5]])
print(c)

[[6 4 5 6]
 [7 6 7 7]
 [6 6 6 6]
 [4 4 6 5]]


In [11]:
# we can use statistics function in our numpy array.
print(np.min(c))
print(np.max(c))
print(np.mean(c))
print(np.sum(c))

4
7
5.6875
91


In [12]:
# we can use the axis arguement and set that equals to 1 for doing statistics function for every column
print(np.min(c,axis=1))
print(np.max(c,axis=1))
print(np.mean(c,axis=1))
print(np.sum(c,axis=1))

[4 6 6 4]
[6 7 6 6]
[5.25 6.75 6.   4.75]
[21 27 24 19]


In [13]:
# we can use the axis arguement and set that equals to 0 for doing statistics function for every row
print(np.min(c,axis=0))
print(np.max(c,axis=0))
print(np.mean(c,axis=0))
print(np.sum(c,axis=0))

[4 4 5 5]
[7 6 7 7]
[5.75 5.   6.   6.  ]
[23 20 24 24]


In [3]:
# we can print the cumulative sum of the array using cumsum() method.
print(np.cumsum(c))
# we can also print the cumulative sum along each row and column.
print(np.cumsum(c,axis=1))
print(np.cumsum(c,axis=0))

[ 6 10 15 21 28 34 41 48 54 60 66 72 76 80 86 91]
[[ 6 10 15 21]
 [ 7 13 20 27]
 [ 6 12 18 24]
 [ 4  8 14 19]]
[[ 6  4  5  6]
 [13 10 12 13]
 [19 16 18 19]
 [23 20 24 24]]


In [58]:
# thers more statictical functions that we can use in numpy.
# to learn more we can go to this following link-
"https://numpy.org/devdocs/reference/routines.statistics.html?highlight=statistics"

'https://numpy.org/devdocs/reference/routines.statistics.html?highlight=statistics'

# Order statistics

In [21]:
print(c)

print(np.amin(c))
print(np.amin(c,axis=0))
print(np.amin(c,axis=1))

print(np.amax(c))
print(np.amax(c,axis=0))
print(np.amax(c,axis=1))

k=np.array([[2,3,5],
            [np.nan,8,1],
            [np.nan,0,np.nan]])

print(np.nanmin(k))
print(np.nanmax(k))

print(np.ptp(c,axis=0)) # max-min

print(np.percentile(c,2,axis=0))
print(np.nanpercentile(k,2,axis=0))

print(np.quantile(c,1,axis=0))
print(np.nanquantile(k,1,axis=0))

[[6 4 5 6]
 [7 6 7 7]
 [6 6 6 6]
 [4 4 6 5]]
4
[4 4 5 5]
[4 6 6 4]
7
[7 6 7 7]
[6 7 6 6]
0.0
8.0
[3 2 2 2]
[4.12 4.   5.06 5.06]
[2.   0.12 1.08]
[7 6 7 7]
[2. 8. 5.]


# Averages and variances

In [29]:
print(np.median(c))
print(np.median(c,axis=1))

print(np.mean(c))
print(np.average(c))

print(np.std(c))
print(np.var(c))

print(np.nanmedian(k))
print(np.nanmean(k))
print(np.nanstd(k))
print(np.nanvar(k))

6.0
[5.5 7.  6.  4.5]
5.6875
5.6875
0.982264602843857
0.96484375
2.5
3.1666666666666665
2.6718699236468995
7.138888888888889


# Correlating

In [49]:
print(np.corrcoef(c))

print()

print(np.correlate([1, 2, 3], [0, 1, 0.5]))
print(np.correlate([1, 2, 3], [0, 1, 0.5], "same"))
print(np.correlate([1, 2, 3], [0, 1, 0.5], "full"))

print()

print(np.cov(c))

[[1.         0.87038828        nan 0.09090909]
 [0.87038828 1.                nan 0.52223297]
 [       nan        nan        nan        nan]
 [0.09090909 0.52223297        nan 1.        ]]

[3.5]
[2.  3.5 3. ]
[0.5 2.  3.5 3.  0. ]

[[0.91666667 0.41666667 0.         0.08333333]
 [0.41666667 0.25       0.         0.25      ]
 [0.         0.         0.         0.        ]
 [0.08333333 0.25       0.         0.91666667]]


# Histograms

In [71]:
for array in np.histogram(c):
    print(array)

print()

xedges = [0, 1, 3, 5]
yedges = [0, 2, 3, 4, 6]
x = np.random.normal(2, 1, 100)
y = np.random.normal(1, 1, 100)
H, xedges, yedges = np.histogram2d(x, y, bins=(xedges, yedges))
print(H)
    
print()

r = np.random.randn(100,3)
H, edges = np.histogramdd(r, bins = (5, 8, 4))
print(H.shape, edges[0].size, edges[1].size, edges[2].size)

[3 0 0 2 0 0 8 0 0 3]
[4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1 6.4 6.7 7. ]

[[10.  4.  0.  0.]
 [43.  4.  1.  0.]
 [10.  6.  0.  0.]]

(5, 8, 4) 6 9 5


In [69]:
print(np.bincount(np.array([0, 1, 1, 3, 2, 1, 7])))
print(np.histogram_bin_edges(c))

x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
print(inds)

for n in range(x.size):
    print(bins[inds[n]-1], "<=", x[n], "<", bins[inds[n]])

[1 3 1 1 0 0 0 1]
[4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1 6.4 6.7 7. ]
[1 4 3 2]
0.0 <= 0.2 < 1.0
4.0 <= 6.4 < 10.0
2.5 <= 3.0 < 4.0
1.0 <= 1.6 < 2.5
