In [1]:
# module 11

import numpy as np
# lets initialize an array.
t=np.array([[1,2,3,4],[5,6,7,8]])
print(t)
print(t.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [2]:
# lets convert the array to an (8,1) array
# we can use the reshape() method.
r=t.reshape([4,2])
# here we have to pass the desired shape as the arguement.
print(r)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
# we can also make a 3d array from 2d array.
r=t.reshape([2,2,2])
print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
# we can stack the arrays vertically by vstack() method.
np.vstack([v1,v2])
# we have to pass the arrays in a list as the arguement.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# we can keep passing the arrays.
np.vstack([v1,v2,v2,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [6]:
# horizontal stacking vectors.
# they are pretty simmilar to vertical stacks.
h1=np.ones([2,5])
h2=np.zeros([2,2])
# we can use hstack() method to stack arrays vertically.
np.hstack([h1,h2,h2])

array([[1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.]])

In [7]:
# concatenate two arrays
# what we have done so far by stacking two arrays vertically and horizontally is called concatenation.
# we have another function called concatenate().
# we can do the operations with this function too.
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.concatenate([v1,v2],axis=0))

print()

h1=np.ones([2,5])
h2=np.zeros([2,2])
print(np.concatenate([h1,h2],axis=1))

[1 2 3 4 5 6 7 8]

[[1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0.]]


In [8]:
# creating a 1d array from multidimentional array.
# we can do that by ravel() function.
a=np.array([[5,4,7,4,2],[2,3,4,5,6]])
print(a)
k=np.ravel(a)
print(k)
# we can also use the flatten() function.
p=a.flatten()
# note that: we have to call this function from array object not from numpy module. 
print(p)

[[5 4 7 4 2]
 [2 3 4 5 6]]
[5 4 7 4 2 2 3 4 5 6]
[5 4 7 4 2 2 3 4 5 6]
