In [1]:
# module 12
import numpy as np

Load Data From File

In [2]:
# sometimes we have data full of information.
# lets say, we dont want to use pandas instead of that we want to read that file 
# and load that data into a numpy array.

# if our data is in a .txt file then we can use genfromtxt() function.
file_data=np.genfromtxt("data.txt",delimiter=",")
# here we have to pass the location of the file first and then we have to pass the delimiter arguement.
# delimiter means the separator which is comma for our case
print(file_data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [3]:
# we can see that all of the data is automatically turned into a float64 type.
# we can change the type in two method.
# the first method is to use dtype arguement when we load in the data.
# the second method is that we can use astype() method to change the datatype.
file_data.astype("int32")

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [4]:
print(file_data)
# but if we run that again we can see that it doesn't change the array permanenetly.
# numpy doesn't have inplace arguement like pandas.
# so we have to do it manually.
file_data=file_data.astype("int32")
print(file_data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking and Advanced Indexing (Filtering)

In [5]:
# this is a pretty cool thing that we can do with numpy.

# boolean maxing means if we write a line(more like a filter), 
# then it will give us a maxk of our array with boolean values.
filt=(file_data>20)
filt

array([[False, False,  True, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [6]:
# we can even grab the values using the filt.
file_data[filt]

array([ 21, 196,  75,  34,  42,  33, 766,  75,  55,  22,  33, 999,  78,
        76,  88])

In [7]:
# we can also mask all the the columns through condition.
# to do that we can use any() method.
# it just tells us if any value of the column supports our condition or not.
np.any(file_data>50,axis=0)
# here we have to arguements first one is the filter 
# and the second one is the axis which is equal to 0, that means we want to run this mask through columns

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [8]:
# we can also use the all() method.
# it just tells us if all value of the column supports our condition or not.
np.all(file_data>10,axis=0)

array([False,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [9]:
# if  we want to do this operation through rows instead of columns, then we can set the axis column equal to 1
print(np.any(file_data>10,axis=1))
print(np.all(file_data>10,axis=1))

[ True  True  True]
[False False False]


In [10]:
# we can also filter by multiple condition,
# we can add multiple condition by & or |
filt=(file_data>50) & (file_data<100)
print(filt)
print(file_data[filt])

[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
[75 75 55 78 76 88]


In [11]:
filt=(file_data<50) | (file_data>100)
print(filt)
print(file_data[filt])

[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
[  1  13  21  11 196   4   3  34   6   7   8   0   1   2   3   4   5   3
  42  12  33 766   4   6   4   3   4   5   6   7   0  11  12   1  22  33
  11 999  11   2   1   0   1   2   9   8   7   1]


In [12]:
# we can also use the tilda(~) sign for inverse filter.
filt=(file_data<50) | (file_data>100)
print(filt)
print(file_data[~filt])

[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
[75 75 55 78 76 88]


In [13]:
# challange
c=np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [14]:
print(c[2:4,0:2])

[[11 12]
 [16 17]]


In [15]:
print(c[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [16]:
print(c[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
