In [9]:
# module 13
import numpy as np

In [10]:
# in numpy documentation, we can see that
# Structured arrays are ndarrays whose datatype is a composition 
# of simpler datatypes organized as a sequence of named fields. 

# it means structured array are special kind of ndarrays which elements are tuple 
# and we can change the datatype of each element of the tuple and can name the fields too.
# lets see an example-
x=np.array([("Rex", 15, 61.3),
            ("Max", 31, 66.0),
            ("Jaz", 12, 42.5)], dtype=[("name","|U5"),("age","int"),("weight","float")])
print(x)

[('Rex', 15, 61.3) ('Max', 31, 66. ) ('Jaz', 12, 42.5)]


In [11]:
# we can see that it gives us an 1d array.
# here each tuples called a "structure".
# if we index the array we will get an structure.
x[2]

('Jaz', 12, 42.5)

In [15]:
# creating dtypes for structured arrays.

# when we created out structured array we set our datatype arguement like this.
# dtype=[("name","|U5"),("age","int"),("weight","float")]

# actually the generalise form is
# dtype=[(FieldName,DataType,shape)]
# here shape is optional. it indicates the sub array shape if we have one in our array.
# field names are generally string, or tuples if titles are used.

In [20]:
# we can see all our columns name by names attribute of dtype attribute.
print(x.dtype.names)

# if we want to see the field names as keys and datatypes and byte offsets as values of a dictionary,
# we can use the fields attribute instead.
print(x.dtype.fields)

('name', 'age', 'weight')
{'name': (dtype('<U5'), 0), 'age': (dtype('int32'), 20), 'weight': (dtype('float64'), 24)}


In [21]:
# You can access and modify individual fields of a structured array by indexing with the field name.
print(x["age"])

# modifying the structured arrays.
x["age"]=[15,32,12]
print(x["age"])

# we can also grab single elements and modify them too.
x["age"][0]=20
print(x["age"])

[20 32 12]
[15 32 12]
[20 32 12]


In [39]:
# we can also see the elements by general indexing.
print(x[0][0])
# here whats going on is that we are first grabbing a structure by x[0],
# and then grabbing the first value of that structure.

# accessing multiple structures.
print(x[1:])
print(x[[0,2]])

Rex
[('Max', 32, 66. ) ('Jaz', 12, 42.5)]
[('Rex', 20, 61.3) ('Jaz', 12, 42.5)]


In [ ]:
# structured arrays are useful when we are working with different fields.
# and we want to grab the values by field names and modify them.