In [16]:
# module 2
# first we need to install numpy with pip
"pip install numpy"

'pip install numpy'

In [2]:
# then we need to import numpy
import numpy as np
# this is a convention.

In [3]:
# initialize a array
# we can do this with array() function
a=np.array([1,2,3])
# here we have to pass in a list as the arguement.
# this is basically a single dimentional array.
a

array([1, 2, 3])

In [4]:
# another important thing is that all the values of an array must be single datatypr
h=np.array([[3,"fu",1,3],[4,9,3,5]])
print(h)
# in this case we can see that, when we have a string in our array, all the values is turned into a string
# if we print out the datatype of the array.
print(h.dtype)
# it is saying us u11
# that means unicode character which actually means string.

[['3' 'fu' '1' '3']
 ['4' '9' '3' '5']]
<U11


In [5]:
print(a)
# we can also initialize an numpy array by arange() function.
# arange() just work like range(), but instead of creating a list, it creates a numpy array.
v=np.arange(2,15,2)
print(v)

[1 2 3]
[ 2  4  6  8 10 12 14]


In [6]:
# we can crete complex multi dimentional array too.
b=np.array([[1.2,2.8,3.3],[4.7,5.2,6.1]])
# here we have to use list inside list.
b

array([[1.2, 2.8, 3.3],
       [4.7, 5.2, 6.1]])

In [7]:
print(b)

[[1.2 2.8 3.3]
 [4.7 5.2 6.1]]


In [8]:
# we can keep doing this we can nest list within list and create 3 dimentional array etc.
c=np.array([[[1,2,3],[4,5,6]],[[5,7,4],[8,3,2]],[[3,4,5],[8,7,5]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 7, 4],
        [8, 3, 2]],

       [[3, 4, 5],
        [8, 7, 5]]])

In [9]:
# get dimension
# we can get the dimenetion of numpy arrays by ndim attribute
# ndim stands for number of dimention
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [10]:
# get shape
# we can get the dshape of numpy arrays by shape attribute
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 2, 3)


In [11]:
# get datatype
# we can also get the datatype of an array by dtype attribute
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int32


In [12]:
# we can also specify what datatype we want when we are creating the array by dtype arguement
d=np.array([3,5,9],dtype="int8")
print(d.dtype)

int8


In [13]:
# get size
# we can see the size of different arrays elements by itemsize attribute.
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print(d.itemsize)
# this will give us the size in bytes.
# basically, 1 byte = 8 bit
# so, int32 = 4 byte and so on.

4
8
4
1


In [14]:
# we can see the number of elements by size attribute
print(a.size)

3


In [15]:
# total size
# we can see the total size in two methods.
# method 1
print(a.size*a.itemsize)
# method 2
# we can use nbytes attribute
# n bytes stands for number of bytes
print(a.nbytes)

12
12
