In [2]:
# module 3

import numpy as np
# Accessing or changing specific rows, elements, columns etc.
# accessing values from a 1d array is pretty much like a list.
# we can do slicing too.
a=np.array([3,4,5,6,7,2])
print(a)
print(a[5])
print(a[1:4])

[3 4 5 6 7 2]
2
[4 5 6]


In [3]:
# we can even grab the values using list in numpy.
print(a[[2,3,5]])
# this looks little awkward as there is list inside list but it works like that.

[5 6 2]


In [4]:
# Accessing or changing specific rows, elements, columns etc. in 2D array.
b=np.array([[1,3,4,2,5,6,7],[4,8,3,5,2,3,7]])
b.shape

(2, 7)

In [5]:
print(b)

[[1 3 4 2 5 6 7]
 [4 8 3 5 2 3 7]]


In [6]:
# get a specific element "array[row, column]"
# note, in pandas counting start with 0
# lets print 8 from our array.
b[1,1]

8

In [7]:
# here we can also use the negative index like list.
b[-1,-6]

8

In [8]:
# we can also mix positive and negative index.
b[1,-6]

8

In [9]:
# get a specific row.
b[0]
# we can do this too.
b[0,:]

# this are pretty much loc[] indexer in pandas.
# actually, pandas is build on numpy.

array([1, 3, 4, 2, 5, 6, 7])

In [10]:
# get a specific column
# here we cant use
# b[,5]
# that will give us an error.
# instead of that we can use slice in the space of the rows
b[:,5]

array([6, 3])

In [11]:
# little more complex with slicing
b[0,1:6:2]
# note that, slicing in numpy is exclusive.

array([3, 2, 6])

In [12]:
# now that we have looked at how to get specific value from a 2d array,
# lets look at how to get values from a 3d array.
c=np.array([[[1,2,3],[4,5,6]],[[5,7,4],[8,3,2]],[[3,4,5],[8,7,5]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[5 7 4]
  [8 3 2]]

 [[3 4 5]
  [8 7 5]]]


In [13]:
# lets say we want to print the 7 of our last line of our array.
c[2,1,1]

7

In [14]:
# we want to print every second line of our 3d array
c[:,1,:]

array([[4, 5, 6],
       [8, 3, 2],
       [8, 7, 5]])