In [2]:
# module 4

import numpy as np

# modifying a single data in a 1d array is also like a list.
# we can modify multiple of values at once by using slicing.
a=np.array([3,4,5,6,7,2])
print(a)
a[3]=90
print(a)
a[2:4]=[76,33]
print(a)
a[3:5]=5
print(a)

[3 4 5 6 7 2]
[ 3  4  5 90  7  2]
[ 3  4 76 33  7  2]
[ 3  4 76  5  5  2]


In [4]:
# modifying 2D array
# changing a single element
b=np.array([[1,3,4,2,5,6,7],[4,8,3,5,2,3,7]])
print(b)
b[1,5]=90
print(b)

[[1 3 4 2 5 6 7]
 [4 8 3 5 2 3 7]]
[[ 1  3  4  2  5  6  7]
 [ 4  8  3  5  2 90  7]]


In [5]:
# chaning a entire column
print(b)
b[:,3]=[88,34]
print(b)

[[ 1  3  4  2  5  6  7]
 [ 4  8  3  5  2 90  7]]
[[ 1  3  4 88  5  6  7]
 [ 4  8  3 34  2 90  7]]


In [6]:
# we can also make all the element of a column a single element.
print(b)
b[:,3]=9
# all we have to do is that we need to just pass a single value instead of a list.
print(b)

[[ 1  3  4 88  5  6  7]
 [ 4  8  3 34  2 90  7]]
[[ 1  3  4  9  5  6  7]
 [ 4  8  3  9  2 90  7]]


In [7]:
# modifying 3d array.
# just like other array we have to first select the chunk that we want to modify,
# after thate we will set that chunk equal to our desired value.
c=np.array([[[1,2,3],[4,5,6]],[[5,7,4],[8,3,2]],[[3,4,5],[8,7,5]]])
print(c)
c[:,1,:]=[[3,5,2],[6,4,1],[0,0,1]]
print("\n")
print(c)

[[[1 2 3]
  [4 5 6]]

 [[5 7 4]
  [8 3 2]]

 [[3 4 5]
  [8 7 5]]]


[[[1 2 3]
  [3 5 2]]

 [[5 7 4]
  [6 4 1]]

 [[3 4 5]
  [0 0 1]]]
