       !! CAUTION !!
!! BE VERY VERY CAREFUL !!

In [2]:
# module 7

import numpy as np
# we need to be very careful when we are doing copying with arrays.
a=np.array([3,5,2])
print(a)

# lets say we need another array "b" and it will be a copy of "a" 
b=a
print(b)

# now if we need to change the values of b for some kind of reason.
b[0]=88
print(b)

# that works fine but if we print the "a"
print(a)

# we can see that a is also being modified when we modified the b array.
# thats not what we want.
# that is happening because when we say b=a,
# we tells numpy that a and b are same object, we didnt tell it to make a copy of a.
# we can see that with id() method.
print(id(a))
print(id(b))
# it tells us a and b have the same id in the memory.
print( a is b)
# it will return True

# this is called "ALIASING".
# we can change the same object using different variables.

[3 5 2]
[3 5 2]
[88  5  2]
[88  5  2]
1739320463968
1739320463968
True


In [3]:
# now we can copy this array with view() method.
print(a)
d=a.view()
# this will create a "Shallow copy"
d[0]=11
print(d)
print(a)
print(id(a))
print(id(d))
print(a is d)
# we can see that a and d are two different object.
# even they poses differnt id in the memory.
# but still they are connected. if we change one, another one get changed too.
# this is the concept of "Shallow copy".

[88  5  2]
[11  5  2]
[11  5  2]
1739320463968
1739323353568
False


In [4]:
# if we want to prevent this problem, then we should use the copy() method instead of just equal to sign.
print(a)
c=a.copy()
print(c)
c[0]=9
print(c)
print(a)
print(id(c))
print(id(a))
print(c is a)
# this is called "Deep copy"
# there are two different arrays with the same value but they are not connected to each other.

[11  5  2]
[11  5  2]
[9 5 2]
[11  5  2]
1739217256736
1739320463968
False
