In [4]:
# module 9

import numpy as np
# all we have done here that was element-wise arithmatic.
# but linear algebra is pretty difference.

# first lets took two arrays of different shape.
a=np.ones([2,3])
print(a)
b=np.full([3,5],2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [5]:
# now if we try to multiply them then it will give us an error as they are not same shape.
a*b
# ValueError: operands could not be broadcast together with shapes (2,3) (3,5) 

ValueError: operands could not be broadcast together with shapes (2,3) (3,5) 

In [6]:
# but in matrix we can multiply them.
# we can do that with matmul() method.
np.matmul(a,b)

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [7]:
# find the determinent
c=np.random.randint(4,8,size=[4,4])
print(c)
# we can find the determinent using det() function from linalg class which just stands for linear algebra
print(np.linalg.det(c))

[[7 5 7 4]
 [4 5 7 7]
 [7 7 5 4]
 [7 5 6 6]]
-209.99999999999994


In [9]:
# find the inverse of the matrix.
# we can use the inv() method from linalg class.
print(c)
print()
i=np.linalg.inv(c)
print(i)

[[7 5 7 4]
 [4 5 7 7]
 [7 7 5 4]
 [7 5 6 6]]

[[ 0.02380952 -0.26666667 -0.07142857  0.34285714]
 [-0.11904762  0.13333333  0.35714286 -0.31428571]
 [ 0.38095238  0.13333333 -0.14285714 -0.31428571]
 [-0.30952381  0.06666667 -0.07142857  0.34285714]]


In [10]:
# Diagonal elements
# there a concept of digonal elements in matrix.
# we can print the digonal elements by diagonal() function.
print(np.diagonal(c))

[7 5 5 6]


In [11]:
# we can convert the numpy arrays to matrix and can do more operations with them.
# we can convert numpy array to matrics by matrix() function.
mat1=np.matrix(c)
print(mat1)
# we can also create matrix with string without arrays.
mat2=np.matrix("1,2,3;4,5,6;7,8,9")
print(mat2)
# matrix and array look same. but they are different type.
print(type(c))
print(type(mat1))

# operations of matrix
# first lets see all the functions that we can do with matrix.
print(dir(mat1))
# lets explore some of them.

# for matrix multiplication we need not use the matmul() method anymore.
# we can easily multiply two matrix.
print(a)
print(b)
mat_a=np.matrix(a)
mat_b=np.matrix(b)
print(mat_a*mat_b)

[[7 5 7 4]
 [4 5 7 7]
 [7 7 5 4]
 [7 5 6 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
<class 'numpy.matrix'>
['A', 'A1', 'H', 'I', 'T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__

In [12]:
# we can find more information about linear algebra in this location.
"https://docs.scipy.org/doc/numpy/reference/routines.linalg.html"

'https://docs.scipy.org/doc/numpy/reference/routines.linalg.html'