In [2]:
# module 9

import numpy as np
# all we have done here that was element-wise arithmatic.
# but linear algebra is pretty difference.

# first lets take two arrays of different shape.
a=np.ones([2,3])
print(a)
b=np.full([3,5],2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [5]:
# now if we try to multiply them then it will give us an error as they are not same shape.
a*b
# ValueError: operands could not be broadcast together with shapes (2,3) (3,5) 

ValueError: operands could not be broadcast together with shapes (2,3) (3,5) 

In [3]:
# but in matrix we can multiply them.
# we can do that with matmul() method. matmul refers to matrix multiply.
print(np.matmul(a,b))
# we can also use the @ sign or dot() method.
print(a @ b)
print(a.dot(b))

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [7]:
# find the determinent
c=np.random.randint(4,8,size=[4,4])
print(c)
# we can find the determinent using det() function from linalg class which just stands for linear algebra.
print(np.linalg.det(c))

[[4 4 6 7]
 [7 4 5 4]
 [4 5 4 7]
 [6 4 6 5]]
-22.000000000000014


In [9]:
# find the inverse of the matrix.
# we can use the inv() method from linalg class.
print(c)
print()
i=np.linalg.inv(c)
print(i)

[[7 5 7 4]
 [4 5 7 7]
 [7 7 5 4]
 [7 5 6 6]]

[[ 0.02380952 -0.26666667 -0.07142857  0.34285714]
 [-0.11904762  0.13333333  0.35714286 -0.31428571]
 [ 0.38095238  0.13333333 -0.14285714 -0.31428571]
 [-0.30952381  0.06666667 -0.07142857  0.34285714]]


In [3]:
# we can see the transpose matrix by transpose() function.
k=np.array([[1,2,3,4],
            [9,8,7,6]])
k_t=np.transpose(k)
print(k_t)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [10]:
# Diagonal elements
# there a concept of digonal elements in matrix.
# we can print the digonal elements by diagonal() function.
print(np.diagonal(c))

[7 5 5 6]


In [5]:
# identity matrix
# we can see the identity matrix by identity() function.
print(np.identity(4))
print()

# we can also use the eye() function.
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# trace()
# we can find the trace of a matrix using trace() function.
print(np.trace(c))

17


In [11]:
# we can convert the numpy arrays to matrix and can do more operations with them.
# we can convert numpy array to matrix by matrix() function.
mat1=np.matrix(c)
print(mat1)
# we can also create matrix with string without arrays.
mat2=np.matrix("1,2,3;4,5,6;7,8,9")
print(mat2)
# matrix and array look same. but they are different type. we can see that with type() method.
print(type(c))
print(type(mat1))

# operations of matrix
# first lets see all the functions that we can do with matrix.
print(dir(mat1))
# lets explore some of them.

# for matrix multiplication we need not use the matmul() method anymore.
# we can easily multiply two matrix.
print(a)
print(b)
mat_a=np.matrix(a)
mat_b=np.matrix(b)
print(mat_a*mat_b)

[[7 5 7 4]
 [4 5 7 7]
 [7 7 5 4]
 [7 5 6 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
<class 'numpy.matrix'>
['A', 'A1', 'H', 'I', 'T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__

In [12]:
# we can find more information about linear algebra in this location.
"https://docs.scipy.org/doc/numpy/reference/routines.linalg.html"

'https://docs.scipy.org/doc/numpy/reference/routines.linalg.html'

In [1]:
# lets discover some functions of linalg class of numpy.

# matrix and vector products

In [92]:
a=np.array([2,3,3,5,2])
b=np.array([7,8,1,2,2])

c=np.array([[4,8,1],
            [5,5,3]])

d=np.array([[8,5,1],
            [0,5,3],
            [9,8,5]])

e=np.array([[7,6,2],
           [0,5,3],
           [3,4,3]])

f = np.arange(25).reshape(5,5)

print(np.dot(a,b))
print(np.linalg.multi_dot([c,d,e]))
print(np.vdot(a,b))
print(np.inner(a,b))
print(np.outer(c,d))
print(np.matmul(c,d))
print(np.einsum(f,[0,0]))
print(np.tensordot(c,d,axes=0))
print(np.linalg.matrix_power(d,4))
print(np.kron(c,d))

55
[[386 718 385]
 [574 912 461]]
55
55
[[32 20  4  0 20 12 36 32 20]
 [64 40  8  0 40 24 72 64 40]
 [ 8  5  1  0  5  3  9  8  5]
 [40 25  5  0 25 15 45 40 25]
 [40 25  5  0 25 15 45 40 25]
 [24 15  3  0 15  9 27 24 15]]
[[41 68 33]
 [67 74 35]]
60
[[[[32 20  4]
   [ 0 20 12]
   [36 32 20]]

  [[64 40  8]
   [ 0 40 24]
   [72 64 40]]

  [[ 8  5  1]
   [ 0  5  3]
   [ 9  8  5]]]


 [[[40 25  5]
   [ 0 25 15]
   [45 40 25]]

  [[40 25  5]
   [ 0 25 15]
   [45 40 25]]

  [[24 15  3]
   [ 0 15  9]
   [27 24 15]]]]
[[10576 12406  5858]
 [ 6804  8122  3966]
 [18702 21916 10390]]
[[32 20  4 64 40  8  8  5  1]
 [ 0 20 12  0 40 24  0  5  3]
 [36 32 20 72 64 40  9  8  5]
 [40 25  5 40 25  5 24 15  3]
 [ 0 25 15  0 25 15  0 15  9]
 [45 40 25 45 40 25 27 24 15]]


# Decompositions

In [85]:
m = np.array([[1,-2j],[2j,5]])
print(np.linalg.cholesky(m))

for array in np.linalg.qr(d):
    print(array)
    
for array in np.linalg.svd(d):
    print(array)

[[1.+0.j 0.+0.j]
 [0.+2.j 1.+0.j]]
[[-0.66436384  0.22492797 -0.7127609 ]
 [-0.         -0.95364197 -0.30094349]
 [-0.74740932 -0.19993597  0.63356524]]
[[-12.04159458  -9.30109374  -4.40141043]
 [  0.          -5.24305781  -3.63567782]
 [  0.           0.           1.55223485]]
[[-0.55577381  0.51540325 -0.65228442]
 [-0.25117551 -0.85205981 -0.45924388]
 [-0.79248113 -0.09139785  0.6030092 ]]
[16.41600614  4.79194492  1.24579549]
[[-0.70531898 -0.63198049 -0.32113207]
 [ 0.68879033 -0.50385923 -0.52124252]
 [ 0.16760975 -0.5888349   0.79068352]]


# Matrix eigenvalues

In [50]:
for array in np.linalg.eig(d):
    print(array)
for array in np.linalg.eigh(d):
    print(array)
print(np.linalg.eigvals(d))
print(np.linalg.eigvalsh(d))

[ 2.46883701+1.18631197j  2.46883701-1.18631197j 13.06232597+0.j        ]
[[-0.4530326 -0.14318987j -0.4530326 +0.14318987j -0.46800581+0.j        ]
 [ 0.64376453+0.j          0.64376453-0.j         -0.30819068+0.j        ]
 [-0.54315765+0.25456852j -0.54315765-0.25456852j -0.82824457+0.j        ]]
[-6.31479361  6.30424434 18.01054927]
[[ 0.45669964  0.64940752 -0.60802575]
 [ 0.51359006 -0.75053181 -0.41584523]
 [-0.72639568 -0.12235961 -0.67629686]]
[ 2.46883701+1.18631197j  2.46883701-1.18631197j 13.06232597+0.j        ]
[-6.31479361  6.30424434 18.01054927]


# Norms and other numbers

In [59]:
print(np.linalg.norm(c))
print(np.linalg.cond(c))
print(np.linalg.det(d))
print(np.linalg.matrix_rank(d))
print(np.linalg.slogdet(d))
print(np.trace(d))

11.832159566199232
4.706632448592814
98.00000000000004
3
(1.0, 4.584967478670572)
18


# Solving equations and inverting matrices

In [88]:
print(d)
k=np.array([[1, 3, 2],
            [0, 0, 6],
            [7, 5, 4]])

a = np.eye(24)
a.shape = (4, 6, 8, 3)
b=np.random.randn(4,6)

print(np.linalg.solve(d,k))
print(np.linalg.tensorsolve(a,b))

for array in np.linalg.lstsq(d,k):
    print(array)
    
print(np.linalg.inv(d))
print(np.linalg.tensorinv(a))

[[8 5 1]
 [0 5 3]
 [9 8 5]]
[[ 0.7244898   0.54081633 -0.6122449 ]
 [-1.43877551 -0.39795918  1.46938776]
 [ 2.39795918  0.66326531 -0.44897959]]
[[-0.96026353  0.08762613  0.74009123]
 [-0.29189608  0.32065758 -0.56486416]
 [ 1.55423919 -1.09498683 -1.52618322]
 [ 0.41757628 -0.27375958  0.45805361]
 [-1.54515842 -0.319086   -0.49934378]
 [ 2.10612596  0.54537257 -1.01109305]
 [-0.10781215  1.51002074  0.53112812]
 [ 0.37998293  2.75554351 -0.18416336]]
[[ 0.7244898   0.54081633 -0.6122449 ]
 [-1.43877551 -0.39795918  1.46938776]
 [ 2.39795918  0.66326531 -0.44897959]]
[]
3
[16.41600614  4.79194492  1.24579549]
[[ 0.01020408 -0.17346939  0.10204082]
 [ 0.2755102   0.31632653 -0.24489796]
 [-0.45918367 -0.19387755  0.40816327]]
[[[[1. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 1. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 1. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0

<ipython-input-88-b93e0569f648>:13: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  for array in np.linalg.lstsq(d,k):


# Exceptions

In [80]:
print(np.linalg.LinAlgError)

<class 'numpy.linalg.LinAlgError'>
